### ISSUE TITLE
This code looks great!

### ISSUE THREAD

**Issue by surrealdetective** [BarbaraSchwarz/dvp-u3-constellations#1]
I reviewed the code, and you did a great job! 

I liked how you used alpha=0.1 to visualize the line for the 2d graph, which adds to understanding what is being graphed. You also picked out good colors to visualize the graph, which makes the info more accessible and aesthetic. The titles and axis names you added are also very descriptive, which orients the viewer so they know what they're looking at.

A small note on style is that I saw that libraries are imported a few times throughout the code. This created a sense of uncertainty for me, because I get the sense that means something has changed, but on closer inspection it's the same. My preference would just to see these libraries imported once and at the top of the code so it's easy to see. Here are the lines of code:

```
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
```

Overall, great work!

**Comment by BarbaraSchwarz** [comment]
Thanks very much for reviewing Alex; you are quite right about about avoiding repetition in code! Cheers for all your comments!
